<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //中断调用链
        // somePromise
        //     .then(() => { })
        //     .then(() => {
        //         // 终止 Promise 链，让下面的 then、catch 和 finally 都不执行
        //     })
        //     .then(() => console.log('then'))
        //     .catch(() => console.log('catch'))
        //     .finally(() => console.log('finally'))

        //         答案就是在 then /catch 的最后一行返回一个永远 pending 的 promise 即可：

        //         return new Promise((resolve, reject) => { })

        // 这样的话后面所有的 then、catch 和 finally 都不会执行了。



        // 中断promise
        // const request = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve('收到服务端数据')
        //     }, Math.random() * 3000)
        // })
        // function timeoutWrapper(p, timeout = 2000) {
        //     const wait = new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             reject('请求超时')
        //         }, timeout)
        //     })
        //     return Promise.race([p, wait])
        // }
        // const req = timeoutWrapper(request)
        // req.then(res => console.log(res)).catch(e => console.log(e))


        // function abortWrapper(p1) {
        //     let abort
        //     let p2 = new Promise((resolve, reject) => (abort = reject))
        //     let p = Promise.race([p1, p2])
        //     p.abort = abort
        //     return p
        // }

        // const myPromise = new Promise((resolve, reject) => {
        //     // Promise 的异步操作
        //     setTimeout(() => {
        //         resolve('收到服务端数据')
        //     }, Math.random() * 3000)
        // });

        // const wrappedPromise = abortWrapper(myPromise);

        // // 在需要中止 Promise 的地方调用 abort 函数
        // wrappedPromise.abort();

        // // 捕获中止的情况
        // wrappedPromise
        //     .then(res => {
        //         console.log(res)
        //     })
        //     .catch(error => {
        //         console.log('Promise aborted:', error);
        //     });





    </script>
</body>

</html>